import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {  } from "@clerk/nextjs";
import Footer from "@/components/Footer";
import MenuNavbar from "@/components/MenuNavbar";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/providers/Themes";
import Sidebar from "@/components/Navbar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: './shop.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            enableColorScheme
            
          >
            <Header />
            {children}
          </ThemeProvider>
          <Footer />
        </body>
    
    </html>

  );


}
