import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {  } from "@clerk/nextjs";
import Footer from "@/components/Footer";

import Header from "@/components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: './shop.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">   
        <body className={inter.className}>
            <main>
              {children}
            </main>       
          <Footer />
        </body>   
    </html>

  );


}
